project_id = "buslxdknzogtgdnietow"

[functions.send-espaco-invitation]
verify_jwt = false

[functions.process-invitation]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.simulate-ticto-callback]
verify_jwt = false